### PR TITLE
Laravel 9.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l9-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^9.3`. If you would like to also upgrade your tests, you may run the [PHPUnit 9 Shift](https://laravelshift.com/upgrade-phpunit-9) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/google-apiclient.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "pulkitjalan/google-apiclient": "dev-l9-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by mralston** [comment]
The package seems to work in my testing once the dependency has been updated. Upvote this PR 👍

**Comment by wardhache** [comment]
@pulkitjalan Would it be possible to review and possibly merge this Pull Request? We would love to update our project to Laravel 9!

**Comment by fregoe** [comment]
@pulkitjalan Please review and merge this pull request. I want also update my projects to Laravel 9.

**Comment by jason-nabooki** [comment]
Anyone using the `https://github.com/laravel-shift/google-apiclient.git` repo be very careful...it's a very old version of the package. Not sure why. @laravel-shift any thoughts?

**Comment by Nuvm** [comment]
@pulkitjalan Please review and merge this to enable Laravel 9 projects. Thanks!

**Pull request merged**
